jwt:
  secret: 4b4096754e674260fec73f02fb2740208835713166bf2f8528e9070fea4f5ca6f954914eef7d025178d28c19834a41a645e5666033fc17378465874a499f9ebb
server:
  servlet:
    context-path: /transaq

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:transactiondb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    template:
      default-topic: transaction-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        acks: 1
        retries: 10
        schema:
          registry:
            url: http://localhost:8081
