DROP TABLE IF EXISTS TR_TRANSACTION;

CREATE TABLE TR_TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  reference VARCHAR(250) NOT NULL,
  account_iban VARCHAR(250) NOT NULL,
  transaction_date VARCHAR(250) DEFAULT NULL,
  amount VARCHAR(250) DEFAULT NULL,
  fee VARCHAR(250) DEFAULT NULL,
  description VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TR_USER;

CREATE TABLE TR_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

INSERT INTO TR_USER (id, username, password)
VALUES (0, 'appuser', '$2y$12$sAg6qnr4LdoplCjgslYNL.AnaDg8Nee3IgMicpjIn4zgiZ8BEXMpK');